apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: formbuilder-product-page
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: formbuilder-product-page
    spec:
      containers:
      - name: product-page
        image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/formbuilder/formbuilder-product-page:latest
        ports:
        - containerPort: 4567
