apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: formbuilder-product-page
spec:
  tls:
    - hosts:
        - formbuilder-product-page.apps.live-1.cloud-platform.service.justice.gov.uk
  rules:
  - host: formbuilder-product-page.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: formbuilder-product-page
          servicePort: 4567
