apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: formbuilder-product-page-staging
spec:
  tls:
    - hosts:
        - formbuilder-product-page-staging.apps.live-1.cloud-platform.service.justice.gov.uk
  rules:
  - host: formbuilder-product-page-staging.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: formbuilder-product-page-staging
          servicePort: 4567
